# Версия синтаксиса Docker Compose
version: '3.8'

# Определяем сервисы (контейнеры), которые будут запущены
services:
  # 1. Сервис для вашего Flask-приложения
  app:
    # Собирать образ из Dockerfile в текущей директории
    build: .
    # Перезапускать контейнер при ошибках
    restart: always
    # Пробрасываем порт 5000 из контейнера на ваш компьютер
    ports:
      - "5000:5001"
    # Монтируем код проекта в контейнер для "живой" перезагрузки при изменениях
    volumes:
      - ./instance:/app/instance
    # Переменные окружения для подключения к базе данных
    environment:
      # Включаем режим отладки Flask для автоматической перезагрузки
      - FLASK_DEBUG=0
    # Устанавливаем лимиты ресурсов, как вы и просили
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
# Определяем том для хранения данных базы
volumes:
  db_data: